# 02 · Reportes

Responde los puntos 3 y 5 a 10 de la prueba Senior con las vistas gold que crea `01_etl`. Se muestran agosto y septiembre. Estos mismos reportes están en el tablero de Power BI; aquí sirven para validar sus cifras y dejar las respuestas por escrito.

Convención: **diferencia = planeado − real**. Si es negativa, se gastó más de lo planeado.

In [1]:
import os
import subprocess
import sys
from pathlib import Path

import pandas as pd
from IPython.display import Markdown, display
from sqlalchemy import create_engine

REPO_URL = "https://github.com/Juangonzalez09/Technical-Test-IW.git"

if "google.colab" in sys.modules:
    RAIZ = Path("Technical-Test-IW")
    if not RAIZ.exists():
        subprocess.run(["git", "clone", "-q", REPO_URL], check=True)
else:
    RAIZ = Path("..")

def url_base_datos():
    """Azure si existe el secreto DATABASE_URL (Colab) o la variable de entorno; si no, SQLite local."""
    try:
        from google.colab import userdata
        return userdata.get("DATABASE_URL")
    except Exception:
        return os.environ.get("DATABASE_URL") or f"sqlite:///{(RAIZ / 'presupuesto.db').resolve().as_posix()}"


DATABASE_URL = url_base_datos()

# Colab no trae el driver de SQL Server
if "google.colab" in sys.modules and DATABASE_URL.startswith("mssql"):
    subprocess.run([sys.executable, "-m", "pip", "install", "-q", "pymssql"], check=True)

# Con SQLite la base solo existe en la sesión donde se corrió el ETL; si no está, se genera
if DATABASE_URL.startswith("sqlite") and not (RAIZ / "presupuesto.db").exists():
    %run {RAIZ / "notebooks" / "01_etl.ipynb"}

engine = create_engine(DATABASE_URL)
print("Base de datos:", engine.url.render_as_string(hide_password=True) if engine.url.host else "SQLite local")


def consulta(sql):
    return pd.read_sql(sql, engine)


def pesos(valor):
    return f"{valor:,.0f}".replace(",", ".")


def mostrar(df, titulo=None):
    """Muestra la tabla con separador de miles."""
    if titulo:
        display(Markdown(f"**{titulo}**"))
    numericas = df.select_dtypes("number").columns.drop("periodo_id", errors="ignore")
    display(df.style.format(pesos, subset=numericas).hide(axis="index"))

Base de datos: mssql+pymssql://juanadmin:***@presupuestosiw.database.windows.net:1433/presupuesto

## Punto 3 · Ejecución presupuestal por rubro

Por cada rubro de egreso del presupuesto: valor planeado, gasto de cada miembro, total de la familia y diferencia. Las columnas de miembros salen de los datos, así que un miembro nuevo aparece sin cambiar el código.

In [2]:
movimientos = consulta("SELECT * FROM v_movimiento")
ejecucion = consulta("SELECT * FROM v_ejecucion_rubro WHERE tipo = 'egreso'")

por_miembro = movimientos.pivot_table(
    index=["periodo_id", "rubro"], columns="miembro", values="valor", aggfunc="sum", fill_value=0
).reset_index()
miembros = [m for m in por_miembro.columns if m not in ("periodo_id", "rubro")]

reporte = ejecucion.merge(por_miembro, on=["periodo_id", "rubro"], how="left").fillna({m: 0 for m in miembros})
reporte = reporte.rename(columns={"valor_real": "total_familia"})
assert (reporte[miembros].sum(axis=1) - reporte["total_familia"]).abs().max() < 1, "La suma por miembro no cuadra"

for periodo, df in reporte.sort_values(["periodo_id", "rubro"]).groupby("periodo_id"):
    mostrar(df[["rubro", "valor_planeado", *miembros, "total_familia", "diferencia"]], df["periodo"].iloc[0])

**Agosto 2023**

**Septiembre 2023**

En agosto el hijo no tiene gastos porque no hay archivo suyo para ese mes.

## Puntos 5 y 6 · ¿La familia gasta más de lo que gana? ¿Está quedando para ahorrar?

- **Ahorro planeado**: ingresos planeados − egresos planeados (el "Ahorro Esperado" de la hoja).
- **Ahorro real**: ingresos reales − egresos reales.
- **Meta de ahorro**: el CDT para la compra del carro que aparece en el presupuesto.

In [3]:
resumen = consulta("SELECT * FROM v_resumen_mes ORDER BY periodo_id")
resumen["ahorro_planeado"] = resumen["ingreso_planeado"] - resumen["egreso_planeado"]
resumen["ahorro_real"] = resumen["ingreso_real"] - resumen["egreso_real"]
resumen["pct_ahorro_real"] = resumen["ahorro_real"] / resumen["ingreso_real"] * 100

columnas = ["ingreso_planeado", "ingreso_real", "egreso_planeado", "egreso_real",
            "ahorro_planeado", "ahorro_real", "meta_ahorro", "pct_ahorro_real"]
(
    resumen.set_index("periodo")[columnas].T.style
    .format(pesos)
    .format(lambda v: f"{v:.1f} %".replace(".", ","), subset=pd.IndexSlice["pct_ahorro_real", :])
)

**Septiembre.** La familia no gasta más de lo que gana, pero queda casi en cero: entraron 21.574.000 y salieron 21.498.846, así que el ahorro real es de 75.154 (0,3 % del ingreso). **No está quedando suficiente para ahorrar**: la hoja esperaba 1.260.113 y la meta del CDT es de 10.000.000. Del total gastado, 3.212.707 son gastos que no estaban en el presupuesto (punto 9).

**Agosto.** Sí gastó más de lo que ganó: 93.239.595 de egresos contra 19.074.000 de ingresos. El ingreso es menor al planeado porque no hay registro del contrato del hijo. El egreso lo dispara la compra del carro (`INVERSIONES`, 78.314.864), que aparece registrada por papá y por mamá. Sin ese rubro, el egreso habría sido de 14.924.731 y el ahorro de 4.149.269.

Hay que tener en cuenta que varios gastos aparecen repetidos entre miembros (ver `01_etl`, sección 5). Si cada uno se contara una sola vez, el ahorro de septiembre subiría a unos 3,3 millones.

## Punto 7 · Rubros donde se gasta más de lo presupuestado

In [4]:
excedidos = ejecucion[ejecucion["valor_real"] > ejecucion["valor_planeado"]].assign(
    exceso=lambda d: d["valor_real"] - d["valor_planeado"]
)

for periodo, df in excedidos.sort_values(["periodo_id", "exceso"], ascending=[True, False]).groupby("periodo_id"):
    mostrar(df[["rubro", "valor_planeado", "valor_real", "exceso"]], df["periodo"].iloc[0])

**Agosto 2023**

**Septiembre 2023**

Top tres de septiembre:

1. **PAGO TARJETA NUBE**: 1.343.921 por encima. Papá hizo dos pagos a la tarjeta en el mes.
2. **CUOTA CASA**: 500.000 por encima. Papá pagó 2.600.000 de hipoteca y abono, y mamá 1.600.000.
3. **VIAJES**: 377.000 por encima, contra un presupuesto de solo 30.000.

En agosto el primero es **PRESTAMO** (2.000.000 con presupuesto 0), seguido de la tarjeta Nu y viajes.

## Punto 8 · Forma de pago preferida de cada miembro

Se toma como preferida la que más veces usa. También se muestra el valor, porque no siempre coinciden. Solo cuenta egresos; los contratos no son pagos.

In [5]:
formas = consulta("SELECT * FROM v_forma_pago")

for periodo, df in formas.groupby("periodo_id"):
    tabla = df.pivot_table(index="miembro", columns="forma_pago", values="movimientos", aggfunc="sum", fill_value=0)
    tabla["preferida"] = tabla.idxmax(axis=1)
    display(Markdown(f"**{df['periodo'].iloc[0]}** · número de pagos"))
    display(tabla)
    display(Markdown("Valor pagado"))
    display(df.pivot_table(index="miembro", columns="forma_pago", values="valor", aggfunc="sum", fill_value=0).style.format(pesos))

**Agosto 2023** · número de pagos

forma_pago  Credito  Debito  Efectivo preferida
miembro
Mama              0      26         0    Debito
Papa              1      54        61  Efectivo

Valor pagado

**Septiembre 2023** · número de pagos

forma_pago  Credito  Debito  Efectivo preferida
miembro
Hijo              0       0        55  Efectivo
Mama              0      45         0    Debito
Papa              1      58        66  Efectivo

Valor pagado

- **Papá**: efectivo por número de pagos (66 contra 58 con débito en septiembre). Pero en plata usa mucho más el débito (11.989.236 contra 1.432.000), porque con débito paga lo grande: hipoteca, préstamo, tarjeta.
- **Mamá**: débito. Es lo único que usa.
- **Hijo**: efectivo. Es lo único que usa.

## Punto 9 · Gastos que no están en rubros presupuestados

In [6]:
no_presupuestado = consulta("SELECT * FROM v_no_presupuestado")

resumen_np = (
    no_presupuestado.groupby(["periodo_id", "periodo", "rubro"])
    .agg(movimientos=("valor", "size"), valor=("valor", "sum"))
    .reset_index()
    .sort_values(["periodo_id", "valor"], ascending=[True, False])
)
for periodo, df in resumen_np.groupby("periodo_id"):
    mostrar(df[["rubro", "movimientos", "valor"]], df["periodo"].iloc[0])

**Agosto 2023**

**Septiembre 2023**

Detalle:

In [7]:
mostrar(no_presupuestado.sort_values(["periodo_id", "rubro", "fecha"]).drop(columns="periodo_id"))

- **PRESTAMO** (septiembre, 2.000.000): en agosto era un rubro del presupuesto. En septiembre esa fila se cambió por `TECNOLOGIA` y el préstamo siguió.
- **RETIRO CAJERO** (1.000.000 cada mes): sacar efectivo no es un gasto en sí. Si luego se registra en qué se gastó, se cuenta dos veces.
- **CUOTAS DE MANEJO**: el 4x1000 y la cuota de la tarjeta. Son fijos y deberían tener rubro.
- **MEDICINA - MEDICO**: el presupuesto tiene `CITAS MEDICAS` en 0. No se unificaron porque no son lo mismo: aquí hay compras de medicamentos.
- **INVERSIONES** (agosto): la compra del carro.

## Punto 10 · Rubros presupuestados que no se usaron en el mes

In [8]:
sin_uso = consulta("SELECT * FROM v_rubro_sin_uso ORDER BY periodo_id, tipo, rubro")

for periodo, df in sin_uso.groupby("periodo_id"):
    mostrar(df[["rubro", "tipo", "valor_planeado"]], df["periodo"].iloc[0])

**Agosto 2023**

**Septiembre 2023**

- **CDT COMPRA CARRO**: la meta de ahorro de 10.000.000 no tuvo ningún movimiento en ninguno de los dos meses.
- **GATAS** (200.000), **TRANSPORTE BUS** (150.000), **PAGO COOPERATIVA** (100.287) y **CUOTA NETFLIX** (15.000) se presupuestaron y no se usaron. Juntos suman 465.287 al mes.
- **CITAS MEDICAS**, **PAGO GOOGLE** y **TECNOLOGIA** están en 0: existen en la hoja, pero no se planeó gastar en ellos.
- En agosto aparecen además **CONTRATO HIJO**, porque no hay archivo del hijo, y **PAGO INTERNET**, que en septiembre sí se pagó.